# Generated by Django 6.0.3 on 2026-04-25 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
