# Generated by Django 6.0.3 on 2026-04-29 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_song_audio_url_song_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
